services:
  app:
    image: jt196/vanilla-cookbook:stable
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./db:/app/prisma/db
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - app
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
