services:
  app:
    image: jt196/vanilla-cookbook:stable
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./.local/vanilla-cookbook/db:/app/prisma/db
      - ./.local/vanilla-cookbook/uploads:/app/uploads
    restart: unless-stopped
